Showing correct answer for Okta Verify during unusual login attempts
allcloud-io/clisso pull request #369
Opened 2024-01-24 15:04 UTC by uznog

Hello there,

I stumbled upon an issue: Okta can mark login attempt as unusual, requiring to select one of three numbers in Okta Verify. Clisso currently doesn't support it, leading user to guessing which number is correct. 

I've resolved the issue within this PR, but the spinner keeps clearing terminal's content - so the message with correct number is visible very briefly and then gets cleared out.

2024-01-24 15:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/allcloud-io/clisso?pullRequest=369) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/allcloud-io/clisso?pullRequest=369) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/allcloud-io/clisso?pullRequest=369) it.</sub>

2024-02-24 20:07 UTC, bitte-ein-bit commented
Hey @uznog,

thanks a lot for catching this and opening a PR. I've added a code suggestion, can you try if that solves your problem about the text vanishing?

Thank you

2024-03-01 10:37 UTC, uznog commented
Hey @bitte-ein-bit,

I don't see any code suggestions / comments regarding the PR, could you point their location for me?

In the meantime - it seems that the unusual attempts aren't an issue when Google authenticator is configured on your Okta account, which I did - so I can't reproduce the process currently, but hopefully I'll be able to once I detach my Google authenticator.

2024-03-01 10:48 UTC, bitte-ein-bit requested changes
Hey @uznog, 

sorry, I forgot to submit the code comment.

2024-03-01 11:10 UTC, uznog commented
@bitte-ein-bit works like a charm now!

2024-03-01 11:18 UTC, bitte-ein-bit approved these changes

2024-03-01 11:18 UTC, merged